"""catalogo_comercial_y_acuerdos_enterprise

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
Create Date: 2026-10-07 18:51:55.706812

"""

import uuid
from decimal import Decimal
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f6a7b8c9d0e1"
down_revision: Union[str, Sequence[str], None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pentest_products",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name_es", sa.String(length=128), nullable=False),
        sa.Column("name_en", sa.String(length=128), nullable=False),
        sa.Column("description_es", sa.String(length=2000), nullable=False),
        sa.Column("description_en", sa.String(length=2000), nullable=False),
        sa.Column("price_label_es", sa.String(length=128), nullable=False),
        sa.Column("price_label_en", sa.String(length=128), nullable=False),
        sa.Column("price_min_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("price_max_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("credits_required", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("max_budget_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("max_turns", sa.Integer(), nullable=True),
        sa.Column(
            "features", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "limits", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credits_required IS NULL OR credits_required > 0", name="ck_pentest_products_credits"
        ),
        sa.CheckConstraint(
            "max_budget_usd IS NULL OR max_budget_usd > 0", name="ck_pentest_products_budget"
        ),
        sa.CheckConstraint("max_turns IS NULL OR max_turns > 0", name="ck_pentest_products_turns"),
        sa.CheckConstraint(
            "price_max_usd IS NULL OR price_max_usd >= price_min_usd",
            name="ck_pentest_products_max_price",
        ),
        sa.CheckConstraint(
            "price_min_usd IS NULL OR price_min_usd >= 0", name="ck_pentest_products_min_price"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "plan_feature_entitlements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_tier", sa.String(length=32), nullable=False),
        sa.Column("feature_key", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_plan_feature_entitlements_tier_feature",
        "plan_feature_entitlements",
        ["plan_tier", "feature_key"],
        unique=True,
    )
    op.create_table(
        "enterprise_agreements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("price_monthly_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column(
            "included_credits",
            sa.Numeric(precision=18, scale=4),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "discount_pct", sa.Numeric(precision=5, scale=2), server_default="0", nullable=False
        ),
        sa.Column("max_budget_usd", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("max_turns", sa.Integer(), nullable=True),
        sa.Column(
            "features", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "limits", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "special_operations",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "discount_pct >= 0 AND discount_pct <= 100", name="ck_enterprise_agreements_discount"
        ),
        sa.CheckConstraint("included_credits >= 0", name="ck_enterprise_agreements_credits"),
        sa.CheckConstraint(
            "max_budget_usd IS NULL OR max_budget_usd > 0", name="ck_enterprise_agreements_budget"
        ),
        sa.CheckConstraint(
            "max_turns IS NULL OR max_turns > 0", name="ck_enterprise_agreements_turns"
        ),
        sa.CheckConstraint(
            "price_monthly_usd IS NULL OR price_monthly_usd >= 0",
            name="ck_enterprise_agreements_price",
        ),
        sa.CheckConstraint("seats IS NULL OR seats > 0", name="ck_enterprise_agreements_seats"),
        sa.CheckConstraint(
            "valid_until IS NULL OR valid_until > valid_from", name="ck_enterprise_agreements_dates"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_enterprise_agreements_org_dates",
        "enterprise_agreements",
        ["organization_id", "valid_from"],
        unique=False,
    )
    productos = sa.table(
        "pentest_products",
        sa.column("id", sa.UUID()),
        sa.column("slug", sa.String()),
        sa.column("name_es", sa.String()),
        sa.column("name_en", sa.String()),
        sa.column("description_es", sa.String()),
        sa.column("description_en", sa.String()),
        sa.column("price_label_es", sa.String()),
        sa.column("price_label_en", sa.String()),
        sa.column("price_min_usd", sa.Numeric()),
        sa.column("price_max_usd", sa.Numeric()),
        sa.column("credits_required", sa.Numeric()),
        sa.column("max_budget_usd", sa.Numeric()),
        sa.column("max_turns", sa.Integer()),
        sa.column("features", postgresql.JSONB()),
        sa.column("limits", postgresql.JSONB()),
        sa.column("is_active", sa.Boolean()),
    )
    op.bulk_insert(
        productos,
        [
            dict(
                id=uuid.uuid4(),
                slug="rightsized-pentest",
                name_es="Rightsized Pentest",
                name_en="Rightsized Pentest",
                description_es="Pentest ajustado al alcance.",
                description_en="Pentest sized to the scope.",
                price_label_es="$60-$300 / pentest",
                price_label_en="$60-$300 / pentest",
                price_min_usd=Decimal("60"),
                price_max_usd=Decimal("300"),
                credits_required=None,
                max_budget_usd=None,
                max_turns=None,
                features=[],
                limits={},
                is_active=True,
            ),
            dict(
                id=uuid.uuid4(),
                slug="full-audit",
                name_es="Full Audit",
                name_en="Full Audit",
                description_es="Auditoría completa.",
                description_en="Full audit.",
                price_label_es="Desde $2.000 / audit",
                price_label_en="From $2,000 / audit",
                price_min_usd=Decimal("2000"),
                price_max_usd=None,
                credits_required=None,
                max_budget_usd=None,
                max_turns=None,
                features=[],
                limits={},
                is_active=True,
            ),
            dict(
                id=uuid.uuid4(),
                slug="enterprise-pentest",
                name_es="Enterprise Pentest",
                name_en="Enterprise Pentest",
                description_es="Alcance y precio por acuerdo.",
                description_en="Scope and price by agreement.",
                price_label_es="Custom",
                price_label_en="Custom",
                price_min_usd=None,
                price_max_usd=None,
                credits_required=None,
                max_budget_usd=None,
                max_turns=None,
                features=[],
                limits={},
                is_active=True,
            ),
        ],
    )
    entitlements = sa.table(
        "plan_feature_entitlements",
        sa.column("id", sa.UUID()),
        sa.column("plan_tier", sa.String()),
        sa.column("feature_key", sa.String()),
        sa.column("enabled", sa.Boolean()),
    )
    op.bulk_insert(
        entitlements,
        [
            dict(id=uuid.uuid4(), plan_tier=plan, feature_key=feature, enabled=plan == "ENTERPRISE")
            for plan in ("FREE", "PRO", "ENTERPRISE")
            for feature in ("supply_chain", "container_scanning", "internal_network_scanning")
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_enterprise_agreements_org_dates", table_name="enterprise_agreements")
    op.drop_table("enterprise_agreements")
    op.drop_index(
        "ix_plan_feature_entitlements_tier_feature", table_name="plan_feature_entitlements"
    )
    op.drop_table("plan_feature_entitlements")
    op.drop_table("pentest_products")
    # ### end Alembic commands ###
